server:
  port: 8461

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8762/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

spring:
  application:
    name: eureka-feign-client

feign:
  hystrix:
    enabled: true