server:
  port: 8762

eureka:
  instance:
    hostname: localhost
  client:
    #是否要注册到其他Server上
    registerWithEureka: true
    #是否拉取其他节点的服务信息
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/